title = "D&D"
baseurl = ""
theme = "beautifulhugo"
languageCode = "en-us"
canonifyurls = true


# allows raw html to be rendered from markdown files
[markup.goldmark.renderer]
    unsafe= true


[Params]
    homeTitle = "D&D" # Set a different text for the header on the home page
    subtitle = "Tales From The Multiverse"
    mainSections = ["post","posts","worlds"]
    logo = "images/d20-icon.svg" # Expecting square dimensions
    favicon = "images/icons/d20-icon.ico"
    dateFormat = "January 2, 2006"
    commit = false
    rss = true
    comments = true
    readingTime = true
    wordCount = true
    useHLJS = true
    socialShare = true
    delayDisqus = true
    showRelatedPosts = true
    custom_css = ["css/style.css"]
    custom_js = ["js/ui.js"]

[Author]
    name = "Stefan Safranek"
    email = "sjsafranek@gmail.com"
    facebook = "stefan.safranek"
    github = "sjsafranek"
    twitter = "sjsafranek"
    stackoverflow = "users/10135286/stefan"


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Characters"
    url = "characters"
    weight = 2

[[menu.main]]
    name = "Parties"
    url = "parties"
    weight = 3

[[menu.main]]
    name = "Campaigns"
    url = "campaigns"
    weight = 4

#[[menu.main]]
#    name = "Worlds"
#    url = "worlds"
#    weight = 5

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 6

# [[menu.main]]
#     name = "About"
#     url = "pages/about"
#     weight = 4

[[menu.main]]
    name = "Contact"
    url = "pages/contact"
    weight = 10


[taxonomies]
    tag = "tags"
    category = "categories"
    campaigns = "campaigns"
    worlds = "worlds"
    parties = "parties"
