title = "D&D"
baseurl = ""
theme = "beautifulhugo"
languageCode = "en-us"
canonifyurls = true


# allows raw html to be rendered from markdown files
[markup.goldmark.renderer]
    unsafe= true


[Params]
    homeTitle = "D&D" # Set a different text for the header on the home page
    subtitle = "Tales From The Multiverse"
    mainSections = ["post","posts","worlds"]
    logo = "images/d20-icon.svg" # Expecting square dimensions
    favicon = "images/icons/d20-icon.ico"
    dateFormat = "January 2, 2006"
    commit = false
    rss = true
    comments = true
    readingTime = true
    wordCount = true
    useHLJS = true
    socialShare = true
    delayDisqus = true
    showRelatedPosts = true
    custom_css = ["css/style.css"]
    custom_js = ["js/ui.js"]


# [Params.staticman]
#   api = "http://207.154.225.107:3333/v2/connect/sjsafranek/staticman_blog_comments/master/comments"
# [Params.staticman.recaptcha]
#   sitekey = "6LeGeTgUAAAAAAqVrfTwox1kJQFdWl-mLzKasV0v"
#   secret = "hsGjWtWHR4HK4pT7cUsWTArJdZDxxE2pkdg/ArwCguqYQrhuubjj3RS9C5qa8xu4cx/Y9EwHwAMEeXPCZbLR9eW1K9LshissvNcYFfC/b8KKb4deH4V1+oqJEk/JcoK6jp6Rr2nZV4rjDP9M7nunC3WR5UGwMIYb8kKhur9pAic="


#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"


[Author]
    name = "Stefan Safranek"
    email = "sjsafranek@gmail.com"
    facebook = "stefan.safranek"
    github = "sjsafranek"
    twitter = "sjsafranek"
    stackoverflow = "users/10135286/stefan"


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1


[[menu.main]]
    name = "Worlds"
    url = "world/"
    weight = 2

[[menu.main]]
    parent = "Worlds"
    name = "Alarra"
    url = "world/alarra"
    weight = 1

[[menu.main]]
    parent = "Worlds"
    name = "Call of the Dreamers"
    url = "world/call-of-the-dreamers"
    weight = 2

[[menu.main]]
    parent = "Worlds"
    name = "Forgotten Realms"
    url = "world/forgotten-realms"
    weight = 3

[[menu.main]]
    parent = "Worlds"
    name = "The Rusty Tankards"
    url = "world/the-rusty-tankards"
    weight = 4

[[menu.main]]
    parent = "Worlds"
    name = "Twilight Isle"
    url = "world/twilight-isle"
    weight = 5


[[menu.main]]
    name = "Parties"
    url = "parties"
    weight = 3


[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3


# [[menu.main]]
#     name = "Categories"
#     url = "categories"
#     weight = 4


# [[menu.main]]
#     name = "About"
#     url = "pages/about"
#     weight = 4


[[menu.main]]
    name = "Contact"
    url = "pages/contact"
    weight = 5


[taxonomies]
    category = "categories"
    tag = "tags"
    worlds = "world"
    parties = "parties"
    places = "places"
